#!/usr/bin/env bash
ADDBOOK_PORT=6001
ADDBOOK_NODE_NAME=addbook
ADDBOOK_MNESIA_PATH=/opt/addbook/var/mnesia
ADDBOOK_LOG_PATH=/opt/addbook/var/log
ADDBOOK_INDEX_FILE="www/index.html"
ADDBOOK_STATIC_DIR="www"
export ADDBOOK_PORT ADDBOOK_NODE_NAME ADDBOOK_MNESIA_PATH ADDBOOK_LOG_PATH ADDBOOK_INDEX_FILE ADDBOOK_STATIC_DIR
